generated: '2026-09-02'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: verily.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov 27 02:36:17 2026 GMT
  hsts: true
  hsts_max_age: 63072000
- host: support.workbench.verily.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Nov  1 00:34:47 2026 GMT
  hsts: true
  hsts_max_age: 31536000
- host: workbench.verily.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Oct 27 04:01:11 2026 GMT
  hsts: true
  hsts_max_age: 31536000
domains:
- domain: verily.com
  dnssec: true
  caa:
  - 0 issue "pki.goog"
  - 0 issue "awstrust.com"
  - 0 issue "digicert.com"
  - 0 issue "amazontrust.com"
  - 0 issue "letsencrypt.org"
  - 0 issue "sectigo.com"
  spf: true
  dmarc: true
  dmarc_policy: reject
